runtime: php55
api_version: 1
threadsafe: yes

# https://cloud.google.com/appengine/docs/php/config/appconfig#PHP_Warmup_requests
#inbound_services:
#- warmup

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

default_expiration: "30d"

includes:
- config.yaml
- routes.yaml

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?\.zip$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- ^\.idea$

