# Deploy:
# gcloud app deploy app.yaml --project irkfap-com -v prod-1 --quiet

# Run locally:
# dev_appserver.py app.yaml

runtime: php55
api_version: 1
threadsafe: yes


# https://cloud.google.com/appengine/docs/php/config/appconfig#PHP_Warmup_requests
inbound_services:
- warmup


default_expiration: "30d"


handlers:

# Static handlers: MIME types
- url: /(.*\.ico)$
  mime_type: image/x-icon
  static_files: public/\1
  upload: public/(.*\.ico)$
  expiration: "7d"

# Web fonts
- url: /(.*\.eot)$
  mime_type: application/vnd.ms-fontobject
  static_files: public/\1
  upload: public/(.*\.eot)$
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(.*\.ttf)$
  mime_type: application/x-font-ttf
  static_files: public/\1
  upload: public/(.*\.ttf)$
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(.*\.woff)$
  mime_type: application/font-woff
  static_files: public/\1
  upload: public/(.*\.woff)$
  http_headers:
    Access-Control-Allow-Origin: "*"

# Additional mime types
- url: /(.*\.less)$
  mime_type: text/css
  static_files: public/\1
  upload: public/(.*\.less)$

- url: /(.*\.md)$
  mime_type: text/markdown
  static_files: public/\1
  upload: public/(.*\.md)$

- url: /(.*\.(gz|gzip))$
  mime_type: application/gzip
  static_files: public/\1
  upload: public/(.*\.(gz|gzip))$

- url: /(.*\.map)$
  mime_type: application/json
  static_files: public/\1
  upload: public/(.*\.map)$

- url: /(.*(LICENSE|LICENSE\-.*))$
  mime_type: text/plain
  static_files: public/\1
  upload: public/(.*(LICENSE|LICENSE\-.*))$

- url: /(.*\.nuspec)$
  mime_type: text/xml
  static_files: public/\1
  upload: public/(.*\.nuspec)$

- url: /(.*\.(yml|yaml))$
  mime_type: text/yaml
  static_files: public/\1
  upload: public/(.*\.(yml|yaml))$

# Static handlers
#- url: /favicon\.ico
#  static_files: public/favicon.ico
#  upload: public/favicon\.ico

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public/robots\.txt

- url: /humans\.txt
  static_files: public/humans.txt
  upload: public/humans\.txt

- url: /crossdomain\.xml
  static_files: public/crossdomain.xml
  upload: public/crossdomain\.xml

- url: /bower_components
  static_dir: public/bower_components

- url: /fontello
  static_dir: public/fontello
  http_headers:
    Access-Control-Allow-Origin: "*"


# Let's Encrypt (ACME http-01 challenge)
- url: /.well-known/acme-challenge/(.*)$
  mime_type: text/plain
  static_files: ACME/acme-challenge/\1
  upload: ACME/acme-challenge/(.*)$
  secure: never


# Dynamic entry points
- url: /about/?
  secure: always
  script: public/about.php

- url: /donate/?
  secure: always
  script: public/invite.php

- url: /invite/(.*\.js)$
  secure: always
  script: public/invite.js.php

- url: /invite/?
  secure: always
  script: public/invite.php

- url: /status/?
  secure: always
  script: public/status.php

- url: /getip/?
  script: public/getip.php


# Other static files
- url: /(.*\.(html|css|js|map|png|jpg|gif))$
  static_files: public/\1
  upload: public/.*\.(html|css|js|map|png|jpg|gif)$
  http_headers:
    Access-Control-Allow-Origin: "*"


# Main entry point
- url: /
  secure: always
  script: public/index.php

- url: /_ah/warmup
  script: warmup.php
  login: admin


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?\.zip$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- ^\.idea$

