name: app-engine

on:
  push:
    branches:
      - master

jobs:
  deploy-gae:
    name: App Engine Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: import config.yaml
        env:
          CONFIG_YAML: ${{secrets.CONFIG_YAML}}
        run: echo "${CONFIG_YAML}" | base64 -d > config.yaml
      - uses: exelban/gcloud@8f13407
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          VERSION_TAG: ${{ format('{0}-{1}', github.actor, github.sha) }}
        with:
          args: app deploy app.yaml --quiet -v "${VERSION_TAG}"
