name: app-engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    steps:
      - uses: actions/checkout@v1
      - uses: exelban/gcloud@v1.0.0
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml --quiet
